# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v4
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          java:
            - 'astra/**'
            - 'benchmarks/**'
            - 'config/**'
            - 'pom.xml'
    - name: Set up JDK 21
      if: steps.filter.outputs.java == 'true'
      uses: actions/setup-java@v3
      with:
        java-version: '21'
        #  Currently, LTS versions of Eclipse Temurin (temurin) are cached on the GitHub Hosted Runners.
        #  When temurin releases Java 21 we can start using that again
        distribution: 'corretto'
        cache: 'maven'
    - name: Build with Maven
      if: steps.filter.outputs.java == 'true'
      run: mvn -B -Dstyle.color=always package --file pom.xml
